### ISSUE TITLE
Issues with new uproot version

### ISSUE THREAD

**Issue by NiclasEich** [DL4Jets/DeepJet#16]
The Conversion script [in the DeepJetCore-repository](https://github.com/DL4Jets/DeepJetCore/blob/master/bin/convertFromSource.py) fails with a TypeError when executed with the [TrainData_DeepCSV module](https://github.com/DL4Jets/DeepJet/blob/master/modules/datastructures/TrainData_deepFlavour.py#L238) and very likely also with the DeepFlavour module.

The stack trace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/DJC/DeepJetCore/DataCollection.py", line 427, in writeData_async
    td.writeFromSourceFile(tmpinput, self.weighterobjects, istraining = not self.istestdata, outname=newpath)
  File "/usr/share/DJC/DeepJetCore/TrainData.py", line 105, in writeFromSourceFile
    self.readFromSourceFile(filename, weighterobjects, istraining)
  File "/usr/share/DJC/DeepJetCore/TrainData.py", line 81, in readFromSourceFile
    x,y,w = self.convertFromSourceFile(filename, weighterobjects, istraining,  **kwargs)
  File "/afs/cern.ch/work/n/neich/private/BTV-HLT-training-tools/DeepJet/modules/datastructures/TrainData_deepFlavour.py", line 448, in convertFromSourceFile
    truth = reduceTruth(truth_arrays)
  File "/afs/cern.ch/work/n/neich/private/BTV-HLT-training-tools/DeepJet/modules/datastructures/TrainData_deepFlavour.py", line 428, in reduceTruth
    return np.vstack((b+lepb,bb+gbb,c+cc+gcc,uds+g)).transpose()
  File "<__array_function__ internals>", line 6, in vstack
TypeError: no implementation found for 'numpy.vstack' on types that implement __array_function__: [<class 'awkward.highlevel.Array'>]
```

This issue is not present, when using uproot version 3 instead of the newest version uproot 4.

A possible hotfix for that could be changing imports
```python
import uproot
...
```

to

```python
import uproot3 as uproot
...
```

For the module.

**Comment by NiclasEich** [comment]
Aah, I was working on the wrong remote, my bad...
