### ISSUE TITLE
module object not callable while tring to convert root file to training format

### ISSUE THREAD

**Issue by rishabhCMS** [DL4Jets/DeepJet#8]
https://github.com/SwapneelM/DeepJet/blob/master/README.md
the instructions for preprocessing the root file into training format
`convertFromRoot.py -i /path/to/the/root/ntuple/list_of_root_files.txt -o /output/path/that/needs/some/disk/space -c TrainData_myclass`

I used the following command
`convertFromRoot.py -i /eos/user/e/ebols/HLT/DeepNTuple_1p1MJets_changedDeepCSVVtxDef.root -o /afs/cern.ch/work/r/runiyal/DeepJet -c TrainDataDeepJet`

which gave me the following error

> (deepjetpkg) [runiyal@lxplus027 DeepJet]$ convertFromRoot.py -i /eos/user/e/ebols/HLT/DeepNTuple_1p1MJets_changedDeepCSVVtxDef.root -o /afs/cern.ch/work/r/runiyal/DeepJet -c TrainDataDeepJet
Using TensorFlow backend.
INFO:root:infile = /eos/user/e/ebols/HLT/DeepNTuple_1p1MJets_changedDeepCSVVtxDef.root
INFO:root:outPath = /afs/cern.ch/work/r/runiyal/DeepJet
Traceback (most recent call last):
  File "/afs/cern.ch/work/r/runiyal/miniconda3/envs/deepjetpkg/bin/convertFromRoot.py", line 4, in <module>
    __import__('pkg_resources').run_script('DeepJetCore==1.0.0', 'convertFromRoot.py')
  File "/afs/cern.ch/work/r/runiyal/miniconda3/envs/deepjetpkg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/afs/cern.ch/work/r/runiyal/miniconda3/envs/deepjetpkg/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/afs/cern.ch/work/r/runiyal/miniconda3/envs/deepjetpkg/lib/python2.7/site-packages/DeepJetCore-1.0.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/convertFromRoot.py", line 118, in <module>
    infile, traind(class_args) if class_args else traind(), outPath, 
TypeError: 'module' object is not callable

**Comment by SwapneelM** [comment]
The mistake lies in the documentation. You should use trainData_deepCSV as the name of the class. It has been updated to reflect these changes.
